### ISSUE TITLE
Новости: ошибка с редактированием несуществующей записи

### ISSUE THREAD

**Issue by rudenko-v** [milaxcom/mconsole-base-components#4]
Переадресовывать на 404.
Такой же баг в новостях и других контроллерах.

**Comment by mindesik** [comment]
@rudenko-v 
Если хочешь заняться - нужно:
- написать для мконсоли обработчик 404 ошибок (исключая сам проект)
- во всех модулях в методе `edit` заменить `$id` на `edit(Model $object)` - бросает NotFoundHttpException если объект не найден в бд
